# Fetching Data Using Web Scrapping

In [166]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup #library used for web scraping
import time

If response code is 403 then use headers
URL used -> https://www.ambitionbox.com/companies-in-pune
headers = {'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}|

In [6]:
headers = {'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage = requests.get('https://www.ambitionbox.com/companies-in-pune',headers=headers).text

In [7]:
soup = BeautifulSoup(webpage, 'lxml')

In [8]:
# print(soup.prettify())

In [9]:
soup.find_all('h1')[0].text

'\n\t\t\t\tTop 30 Companies in Pune\n\t\t\t'

To find name of comapanies in Pune

In [10]:
len(soup.find_all('h2'))

24

In [14]:
cnt = 0
for i in soup.find_all('h2'):
    if cnt < 21: #beacuse there are 20 companies + 1 'companies in pune' tag (which is h2) and 23 h2 tags
        print(i.text.strip())
    cnt+=1

Companies in Pune
TCS
Accenture
Wipro
Cognizant
Capgemini
HDFC Bank
Infosys
ICICI Bank
HCLTech
Tech Mahindra
Genpact
Teleperformance
Jio
Axis Bank
Concentrix Corporation
Amazon
iEnergizer
Reliance Retail
LTIMindtree
IBM

In [27]:
# for i in soup.find_all('p'):
#     print(i.text.strip())

In [32]:
company = soup.find_all('div', class_='companyCardWrapper')

In [33]:
len(company) # company is a dictionary

20

In [63]:
countRatings = soup.find_all('span', class_='companyCardWrapper__companyRatingCount')

In [64]:
len(countRatings)

20

In [65]:
for i in ratings:
    print(i.text.strip())

(1.1L)
(72k)
(64k)
(60.3k)
(52k)
(51.2k)
(47.8k)
(45.2k)
(45k)
(42.7k)
(41.3k)
(37.2k)
(33.3k)
(32.6k)
(31.6k)
(30.9k)
(27.2k)
(27.1k)
(26k)
(25.4k)

In [69]:
companyType = soup.find_all('div', class_=('companyCardWrapper__tertiaryInformation'))

In [70]:
len(companyType)

20

In [74]:
type(companyType) #basically it's a list

bs4.element.ResultSet

In [75]:
for i in companyType:
    print(i.text.strip())

1.1L Reviews9.9L Salaries11.9k Interviews3k Jobs10.6k Benefits93 Photos
72k Reviews6.5L Salaries9.2k Interviews33.7k Jobs6.7k Benefits49 Photos
64k Reviews4.8L Salaries6.7k Interviews4.8k Jobs4.6k Benefits107 Photos
60.3k Reviews6L Salaries6.3k Interviews568 Jobs5.5k Benefits86 Photos
52k Reviews4.8L Salaries5.5k Interviews2.6k Jobs3.7k Benefits42 Photos
51.2k Reviews1.5L Salaries3k Interviews402 Jobs3.2k Benefits86 Photos
47.8k Reviews5.3L Salaries8.4k Interviews2.3k Jobs4.8k Benefits118 Photos
45.2k Reviews1.5L Salaries2.9k Interviews15 Jobs3.7k Benefits73 Photos
45k Reviews3.8L Salaries4.5k Interviews280 Jobs3.8k Benefits65 Photos
42.7k Reviews2.8L Salaries4.5k Interviews657 Jobs3.4k Benefits79 Photos
41.3k Reviews2.3L Salaries3.8k Interviews1k Jobs3.5k Benefits66 Photos
37.2k Reviews97k Salaries2.2k Interviews2.1k Jobs1.8k Benefits38 Photos
33.3k Reviews61.8k Salaries4.2k Interviews1 Jobs2.5k Benefits87 Photos
32.6k Reviews1L Salaries1.9k Interviews205 Jobs2.1k Benefits120 Photos
31.6k Reviews1.3L Salaries2k Interviews63 Jobs3.1k Benefits66 Photos
30.9k Reviews1.5L Salaries5.8k Interviews1.8k Jobs3.6k Benefits90 Photos
27.2k Reviews24.3k Salaries1.3k Interviews74 Jobs430 Benefits29 Photos
27.1k Reviews76.1k Salaries1.9k Interviews136 Jobs1.8k Benefits135 Photos
26k Reviews1.9L Salaries3.4k Interviews485 Jobs777 Benefits34 Photos
25.4k Reviews2.1L Salaries2.6k Interviews2k Jobs2.6k Benefits23 Photos

In [77]:
companyInfo = soup.find_all('div', class_=('companyCardWrapper'))

In [78]:
len(companyInfo)

20

### Dataframe for 1 Webpage

In [161]:
name = []
rating = []
reviews = []
salary = []
interviews = []
jobs = []
benefits = []


for i in companyInfo:
    name.append(i.find('h2').text.strip()) #find because only 1 company in h2 tag
    rating.append(i.find('div', class_='rating_text rating_text--md').text.strip())

    actions = i.find_all('span', class_='companyCardWrapper__ActionCount')
    reviews.append(actions[0].text.strip())
    salary.append(actions[1].text.strip())
    interviews.append(actions[2].text.strip())
    jobs.append(actions[3].text.strip())
    benefits.append(actions[4].text.strip())    

df = pd.DataFrame({'name':name, 'rating':rating, 'reviews':reviews, 'salary':salary, 'interviews':interviews, 'jobs':jobs, 'benefits':benefits})

In [162]:
df

                      name rating reviews salary interviews   jobs benefits
0                      TCS    3.3    1.1L   9.9L      11.9k     3k    10.6k
1                Accenture    3.7     72k   6.5L       9.2k  33.7k     6.7k
2                    Wipro    3.6     64k   4.8L       6.7k   4.8k     4.6k
3                Cognizant    3.6   60.3k     6L       6.3k    568     5.5k
4                Capgemini    3.7     52k   4.8L       5.5k   2.6k     3.7k
5                HDFC Bank    3.8   51.2k   1.5L         3k    402     3.2k
6                  Infosys    3.5   47.8k   5.3L       8.4k   2.3k     4.8k
7               ICICI Bank    4.0   45.2k   1.5L       2.9k     15     3.7k
8                  HCLTech    3.4     45k   3.8L       4.5k    280     3.8k
9            Tech Mahindra    3.4   42.7k   2.8L       4.5k    657     3.4k
10                 Genpact    3.6   41.3k   2.3L       3.8k     1k     3.5k
11         Teleperformance    3.8   37.2k    97k       2.2k   2.1k     1.8k
12                     Jio    4.4   33.3k  61.8k       4.2k      1     2.5k
13               Axis Bank    3.6   32.6k     1L       1.9k    205     2.1k
14  Concentrix Corporation    3.6   31.6k   1.3L         2k     63     3.1k
15                  Amazon    3.9   30.9k   1.5L       5.8k   1.8k     3.6k
16              iEnergizer    4.6   27.2k  24.3k       1.3k     74      430
17         Reliance Retail    3.9   27.1k  76.1k       1.9k    136     1.8k
18             LTIMindtree    3.6     26k   1.9L       3.4k    485      777
19                     IBM    3.9   25.4k   2.1L       2.6k     2k     2.6k

### Dataframe for top 250 companies in Pune

In [168]:
final = pd.DataFrame()
for j in range(1, 101):
    time.sleep(3)
    headers = {'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
    webpage = requests.get(f"https://www.ambitionbox.com/companies-in-pune?page={j}",headers=headers).text
    soup = BeautifulSoup(webpage, 'lxml')
    company = soup.find_all('div', class_='companyCardWrapper')
    name = []
    rating = []
    reviews = []
    salary = []
    interviews = []
    jobs = []
    benefits = []

    for i in company:
        try:
            name.append(i.find('h2').text.strip()) #find because only 1 company in h2 tag
        except:
            name.append(np.nan)
            
        try:
            rating.append(i.find('div', class_='rating_text rating_text--md').text.strip())
        except:
            rating.append(np.nan)
            
        actions = i.find_all('span', class_='companyCardWrapper__ActionCount')
        
        try:
            reviews.append(actions[0].text.strip())
        except:
            reviews.append(np.nan)
            
        try:
            salary.append(actions[1].text.strip())
        except:
            salary.append(np.nan)
    
        try:
            interviews.append(actions[2].text.strip())
        except:
            interviews.append(np.nan)
    
        try:
            jobs.append(actions[3].text.strip())
        except:
            jobs.append(np.nan)
    
        try:
            benefits.append(actions[4].text.strip())
        except:
            benefits.append(np.nan)
        
    df = pd.DataFrame({'name':name, 'rating':rating, 'reviews':reviews, 'salary':salary, 'interviews':interviews, 'jobs':jobs, 'benefits':benefits})

    final = pd.concat([final, df], ignore_index=True)

In [169]:
final

,name,rating,reviews,salary,interviews,jobs,benefits
0,JoulestoWatts Business Solutions,3.5,649,3.2k,78,2,12
1,SMC Global Securities,3.4,649,2.5k,55,8,26
2,CJ Darcl Logistics Limited,4.0,648,1.9k,44,2,45
3,HCL Healthcare,4.6,648,942,164,22,19
4,Welspun World,3.6,647,2.5k,59,99,81
...,...,...,...,...,...,...,...
255,EID Parry (India),3.9,473,1.5k,25,--,51
256,ASM Technologies,3.5,473,3.4k,45,21,29
257,Teradata,3.6,472,3.7k,62,--,44
258,MathCo,3.0,471,2.9k,133,24,22
259,Clove Dental,4.1,471,1.3k,75,14,10